### ISSUE TITLE
Only dotnet 2 and mshtml?

### ISSUE THREAD

**Issue by benyaminl** [mmtrt/cnctsun#11]
hello, I seen the config, and I tried to replicate it on bare wine, based on this https://github.com/mmtrt/cnctsun/blob/master/snap/snapcraft.yaml#L36-L44 does it only need wine mono, dotnet 2 and mshtml + d3x9?

Or I'm missing something else? Thanks

**Comment by mmtrt** [comment]
it needs wine mono & dotnet2 nothing else

**Comment by benyaminl** [comment]
Anyway I think I found the problem, there are updates on the Installer https://downloads.cnc-comm.com/tiberian-sun/tsins/TSinstaller.exe

It won't fail download dotnetfx. ah... sad... 

Anyway thanks for replying even it's not 100% related to the project!

**Comment by mmtrt** [comment]
you can also try tsun appimage which comes with everything installed so just run it play.

https://github.com/mmtrt/cnctsun_AppImage/releases/download/stable-wp/cnctsun-1.0-x86_64.AppImage
