### ISSUE TITLE
Screen goes black, unresponsive after lowering resolution

### ISSUE THREAD

**Issue by SVaeth** [mmtrt/cnctsun#12]
Resolution set to 1920 x 1080 works, but changing it to any other setting breaks my machine and I have to hard reboot. I would like to be able to zoom in on the game map and possibly made a wider, shorter display for the base operations menu and transmission videos. The current setup is too narrow. But changing the resolution does not work for for the aforementioned issues. I've tried 1080 x 768, 1280 x 1080, etc

![Screenshot from 2023-12-04 23-02-26](https://github.com/mmtrt/cnctsun/assets/40723506/2d6cf2ef-277c-40a9-8800-8f3706bcd1cf)

**Comment by mmtrt** [comment]
Try using wine virtual desktop from `winecfg` in graphics tab.

`cnctsun.wine winecfg`

**Comment by SVaeth** [comment]
So I tried setting emulate a virtual desktop as suggested, but that made it worse/unplayable

![Screenshot from 2023-12-05 07-21-52](https://github.com/mmtrt/cnctsun/assets/40723506/810c37c3-1d75-4c16-b0c1-90603945e402)

**Comment by SVaeth** [comment]
After tinkering with it, I managed to get it working so that I can change resolution. It didn't help my issue with zooming in/making the ui less condensed, but it did resolve this issue, so I'm good to close it. Thank you
